### PR TITLE
Relative path, from another path

### PR DESCRIPTION
**Pull request by gaborcsardi**
Mostly straightforward, this is very slow as well, as I just followed the Python code. Good to merge after #13.

### CODE REVIEW

**Comment by richfitz** [comment]
For the speed things, I vote we don't worry about it for now, and we can always speed things up a ton in C++ pretty easily once the interface is good.

**Comment by gaborcsardi** [comment]
That's what I thought. There is a lot of logic here, so it is near impossible to write fast R code for it. But speed is not my concern, anyway.

**Comment by richfitz** [comment]
I restarted the travis build after merging #13, but this is still failing. I can look into it tomorrow unless you want to now...

**Comment by richfitz** [comment]
Ah, I see you commented already. In your own time 😸

**Comment by gaborcsardi** [comment]
I think it is a `browser()` call, will fix in a minute.

**Comment by gaborcsardi** [comment]
Yeah, still failing. Tomorrow then. :)

**Comment by gaborcsardi** [comment]
Ah, I managed to mock a function with another one that calls the mocked function.......

**Comment by gaborcsardi** [comment]
All good now.

**Comment by richfitz** [comment]
This will be so useful.

**Pull request merged**
